package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.36

import (
	"changeHere/src/data/contracts"
	"changeHere/src/data/graph"
	"context"
)

// CreateTodo is the resolver for the createTodo field.
func (r *mutationResolver) CreateTodo(ctx context.Context, input contracts.NewTodo) (*contracts.Todo, error) {
	a := &contracts.Todo{
		ID:   "1",
		Text: "123",
		Done: false,
		User: nil,
	}
	return a, nil
}

// Todos is the resolver for the todos field.
func (r *queryResolver) Todos(ctx context.Context) ([]*contracts.Todo, error) {
	a := &contracts.Todo{
		ID:   "1",
		Text: "123",
		Done: false,
		User: nil,
	}

	var b []*contracts.Todo

	b = append(b, a)
	return b, nil
}

// Mutation returns graph.MutationResolver implementation.
func (r *Resolver) Mutation() graph.MutationResolver { return &mutationResolver{r} }

// Query returns graph.QueryResolver implementation.
func (r *Resolver) Query() graph.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
